---
title: "Testing"
author: "Michael Battaglia"
date: "7/6/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tibbletest)
```

```{r}

example_dat %>%
  covariate_balance(
    treatment = "treat",
    variables = c("age", "sugar_factor", "gender", "happiness"),
    nonparametric = "age",
    weights = "weight"
  ) %>%
  format_tbl()

```

```{r}

df <- example_dat
treatment <- "treat2"
var <- "happy"
weight_var <- "no_weight"

df <- df %>%
  drop_na(.data[[var]], .data[[treatment]])

weighted_props <- df %>%
  drop_na(.data[[treatment]], .data[[var]]) %>%
  group_by(.data[[treatment]], .data[[var]]) %>%
  summarise_at(
    weight_var,
    sum
  ) %>%
  mutate(p = .data[[weight_var]] / sum(.data[[weight_var]])) %>%
  ungroup()

weighted_props_list <- split(
  weighted_props$p,
  weighted_props[[treatment]]
)

x <- weighted_props_list[1:2]

prop_diff <- x[[1]] - x[[2]]

var_1 <- x[[1]] * (1 - x[[1]])
var_2 <- x[[2]] * (1 - x[[2]])

pooled_sd <- sqrt(
  (var_1 + var_2) / 2
)

abs(100 * prop_diff / pooled_sd) %>%
  max()

calculate_std_diff <- function(y) {

  prop_diff <- y$p[1] - y$p[2]

  var_1 <- y$p[1] * (1 - y$p[1])
  var_2 <- y$p[2] * (1 - y$p[2])
  
  pooled_sd <- sqrt(
    (var_1 + var_2) / 2
  )
  
  abs(100 * prop_diff / pooled_sd)

}
  
x %>%
  group_by(.data[[var]]) %>%
  group_split() %>%
  map_dbl(calculate_std_diff) %>%
  max()


calculate_std_diff_two_groups <- function(x) {
  
  calculate_std_diff <- function(y) {
  
    prop_diff <- y$p[1] - y$p[2]
  
    var_1 <- y$p[1] * (1 - y$p[1])
    var_2 <- y$p[2] * (1 - y$p[2])
    
    pooled_sd <- sqrt(
      (var_1 + var_2) / 2
    )
    
    abs(100 * prop_diff / pooled_sd)
  
  }
  
  x %>%
    group_by(.data[[var]]) %>%
    group_split() %>%
    map_dbl(calculate_std_diff) %>%
    max()
  
}

combn(1:3, 2, simplify = FALSE) %>%
  map(
    ~ weighted_props %>%
      slice(.x)
  ) %>%
  map_dbl(
    calculate_std_diff
  ) %>%
  max()

```
