---
title: "PICO Analysis"
author: "Michael Battaglia"
date: "6/16/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(readxl)
library(tibbletest)
```

## Read Data

```{r}

registry_dat <- read_xlsx("merged-filtered-04-20-2020.xlsx")

mda_dat <- read_xlsx("PICO_E20858_Final_Data_2020_12_29 with Mortality and readmissions.xlsx") %>%
  janitor::clean_names()

dat <- inner_join(
  registry_dat,
  mda_dat,
  by = c("id" = "f_id")
)

```

## Data Cleaning

```{r}

outcomes <- dat %>%
  select(
    dasi_intake, dasi_mets_intake, dasi_discharge, dasi_mets_discharge, 
    readmit90, readmit180, readmit365, mort90, mort180, mort365,
    non_hdl_cholestrol_intake, non_hdl_cholestrol_discharge,
    ldl_cholesterol_intake, ldl_cholesterol_discharge, hemoglobin_a1c_intake,
    hemoglobin_a1c_discharge, sf36_mcs_score_intake, sf36_mcs_score_discharge,
    sf36_pcs_score_intake, sf36_pcs_score_discharge, phq9_score_intake,
    phq9_score_discharge, block_fat_screener_intake, block_fat_screener_discharge,
    rate_your_plate_intake, rate_your_plate_discharge
  ) %>%
  mutate_all(
    as.numeric
  ) %>%
  mutate_at(
    vars(readmit90:mort365),
    as.logical
  )

covariates <- dat %>%
  select(
    age, gender, htn:sleepapnea, intake_tobacco_status, risk_category
  ) %>%
  mutate_at(
    vars(htn:sleepapnea),
    as.logical
  ) %>%
  mutate(
    intake_tobacco_status = recode(
      intake_tobacco_status,
      "Current status unknown" = NA_character_,
      .default = intake_tobacco_status
    ),
    risk_category = recode(
      risk_category,
      "Unknown" = NA_character_,
      .default = risk_category
    )
  )

dat <- bind_cols(
  icr_cr = dat$icr_cr,
  covariates, 
  outcomes
) %>%
  drop_na(htn)

covariates <- colnames(covariates)
outcomes <- colnames(outcomes)

```

## Covariate Table

```{r}

covariates_tbl <- dat %>%
  descriptives(
    treatment = "icr_cr",
    variables = covariates
  ) %>%
  format_tbl()

covariates_tbl_new <- dat %>%
  covariate_balance(
    treatment = "icr_cr",
    variables = covariates
  ) %>%
  format_tbl()

```

## Propensity Weighting

```{r}

dat <- dat %>%
  add_propensity_weights(
    treatment = "icr_cr",
    ivs = covariates,
    impute_missing = TRUE
  )

```

## Adjusted Covariate Table

```{r}

adj_covariates_tbl <- dat %>%
  descriptives(
    treatment = "icr_cr",
    variables = covariates,
    weights = "propensity_weight"
  ) %>%
  format_tbl()

adj_covariates_tbl_new <- dat %>%
  covariate_balance(
    treatment = "icr_cr",
    variables = covariates,
    weights = "propensity_weight"
  ) %>%
  format_tbl()


```

## Love Plots

```{r}

love_plot <- function(unadj, adj) {
  
  unadj <- unadj %>%
    select(
      Variable,
      `Absolute Standardized Difference (%)`
    ) %>%
    mutate(`Absolute Standardized Difference (%)` = as.numeric(`Absolute Standardized Difference (%)`)) %>%
    drop_na() %>%
    distinct() %>%
    rename(
      "Unweighted" = `Absolute Standardized Difference (%)`
    )
  
  adj <- adj %>%
    select(
      Variable,
      `Absolute Standardized Difference (%)`
    ) %>%
    mutate(`Absolute Standardized Difference (%)` = as.numeric(`Absolute Standardized Difference (%)`)) %>%
    drop_na() %>%
    distinct() %>%
    rename(
      "Weighted" = `Absolute Standardized Difference (%)`
    )
  
  plot_dat <- inner_join(
    unadj,
    adj,
    by = "Variable"
  ) %>%
    arrange(desc(Unweighted)) %>%
    mutate(Variable = fct_rev(as_factor(Variable))) %>%
    pivot_longer(
      cols = -Variable,
      names_to = "type",
      values_to = "std_diff"
    )
  
  plot_dat %>%
    ggplot(
      aes(x = Variable, y = std_diff, color = type)
    ) +
    geom_point(size = 2) +
    theme_bw() +
    coord_flip() +
    labs(
      x = NULL,
      y = "Absolute Standardized Difference (%)",
      color = NULL
    ) +
    theme(text = element_text(size = 14)) +
    geom_hline(yintercept=10, lty=2)
  
}

t <- love_plot(
  unadj = covariates_tbl_new,
  adj = adj_covariates_tbl_new
)

```
