#' Preprocesses a tibble to prepare it for presentation in a descriptives table
#'
#' Cleans the variable names, adds variable labels, and converts binary variables to logical in the output tibble
#'
#' @param df <`tbl_df`> Data frame with treatment and variables of interest as columns.
#' @param var_labels <`list`> Named list of column names and descriptive labels. By default, labels will generated by converting column names to title case
#' @param clean_names <`logical`> Should variable names be cleaned with `janitor::clean_names()`?
#' @param convert_to_logical <`logical`> Should binary variables be converted to logical?
#' @param quiet <`logical`> Should messages related to preprocessing changes be suppressed?
#'
#' @return <`tbl_df`>
#'
#' @import dplyr
#' @import purrr
#'
#' @export
preprocess <- function(df, var_labels = NULL, clean_names = TRUE, convert_to_logical = TRUE, quiet = FALSE) {

  if (convert_to_logical == TRUE) {

    pre_logical <- df %>% select_if(is.logical) %>% colnames()

    df <- df %>%
      mutate_if(is.factor, as.character) %>%
      mutate_all(convert_logical)

    post_logical <- df %>% select_if(is.logical) %>% colnames()

    if (!identical(pre_logical, post_logical) & quiet == FALSE) {
      message(paste(
        cat(crayon::italic$bold("[Step 1]: Converting binary variables to logical variables\n")),
        cat(crayon::cyan("Variables (",
                         paste(post_logical[!(post_logical %in% pre_logical)], collapse = ", "),
                         ") were converted to logical.", sep = ""
      ))))
    }
  } else {
    if (quiet == FALSE) {
      message(paste(
        cat(crayon::italic$bold("[Step 1]: Converting binary variables to logical variables\n")),
        cat(crayon::yellow("SKIPPED"))
      ))
    }
  }

  if (clean_names == TRUE) {

    original_vars <- colnames(df)
    cleaned_vars  <- colnames(janitor::clean_names(df))

    df <- janitor::clean_names(df)

    if (identical(original_vars, cleaned_vars) & quiet == FALSE) {
      message(paste(
        cat(crayon::italic$bold("[Step 2]: Cleaning variable names\n")),
        cat(crayon::cyan("All original variable names were clean."))
      ))
    } else {
      if (quiet == FALSE) {
        message(paste(
          cat(crayon::italic$bold("[Step 2]: Cleaning variable names\n")),
          cat(crayon::cyan("The following variable names were cleaned with the mapping:")),
          cat(crayon::cyan(paste(utils::capture.output({
            print(tibble(`Original Name` = original_vars,
                         `Cleaned Name`  = cleaned_vars) %>%
                    filter(`Original Name` != `Cleaned Name`) %>%
                    knitr::kable())
          }), collapse = "\n")))
        ))
      }
    }
  } else {
    if (quiet == FALSE) {
      message(paste(
        cat(crayon::italic$bold("[Step 2]: Cleaning variable names\n")),
        cat(crayon::yellow("SKIPPED"))
      ))
    }
  }

  if (is.null(var_labels)) {
    if (sjlabelled::is_labelled(df) == FALSE) {
      df <- sjlabelled::set_label(df, snakecase::to_title_case(colnames(df)))
    }
  } else {
    if (clean_names == TRUE) {
      names(var_labels) <- var_labels %>%
        names() %>%
        janitor::make_clean_names()
    }

    default_labels <- as.list(setNames(snakecase::to_title_case(colnames(df)), as.list(colnames(df))))

    labels <- default_labels %>%
      as_tibble() %>%
      gather() %>%
      left_join(var_labels %>% as_tibble() %>% gather(value = "new"), by = "key") %>%
      coalesce() %>%
      mutate(label = coalesce(new, value)) %>%
      select(key, label)

    labels <- as.list(setNames(labels$label, as.list(labels$key)))

    df <- sjlabelled::set_label(df, labels)
  }

  if (quiet == FALSE) {
    message(paste(
      cat(crayon::italic$bold("[Step 3]: Adding variable labels\n")),
      cat(crayon::cyan("The following variable labels were specified with the mapping:")),
      cat(crayon::cyan(paste(utils::capture.output({
        print(df %>% sjlabelled::get_label() %>% tibble::enframe(name = "Variable", value = "Label") %>% knitr::kable())
      }), collapse = "\n")))
    ))
  }

  df
}
